swagger: "2.0"
info:
  description: "Definición del servicio de Reservas"
  version: "1.0.0"
  title: "Servicio de Reservas"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "backend-reservas.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "Reservas"
  description: "Reservas de vehículos"
schemes:

- "http"
paths:
  /reservas:
    post:
      tags:
      - "Reservas"
      summary: "Crear una reserva"
      description: ""
      operationId: "createReserva"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/ReservaEntrada"
      responses:
        "200":
          description: "Operación satisfactoria"
          schema:
            type: "string"
        "400":
          description: "Error de validación"
    get:
      tags:
      - "Reservas"
      summary: "Listado de reservas para un usuario"
      description: ""
      operationId: "listaReservas"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Token del usuario"
        required: true
        type: string
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Operación satisfactoria"
          schema:
            type: "array"
            items: 
              type: "object"
              $ref: "#/definitions/Reserva"
  /reservas/{id}:
    get:
      tags:
      - "Reservas"
      summary: "Obtener una reserva para un usuario"
      description: ""
      operationId: "obtenerReserva"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Token del usuario"
        required: true
        type: string
      - in: "path"
        name: "id"
        description: "Identificador de la reserva"
        required: true
        type: string
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Operación satisfactoria"
          schema:
            type: "array"
            items: 
              type: "object"
              $ref: "#/definitions/Reserva"
        "404":
          description: "No encontrada"
    delete:
      tags:
      - "Reservas"
      summary: "Cancelar una reserva para un usuario"
      description: ""
      operationId: "cancelarReserva"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Identificador del usuario"
        required: true
        type: string
      - in: "path"
        name: "id"
        description: "Identificador de la reserva"
        required: true
        type: string
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Operación satisfactoria"
          schema:
            type: "array"
            items: 
              type: "object"
              $ref: "#/definitions/Reserva"
        "404":
          description: "No encontrada"
    patch:
      tags:
      - "Reservas"
      summary: "Inicia una reserva para un usuario"
      description: ""
      operationId: "iniciarReserva"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Identificador del usuario"
        required: true
        type: string
      - in: "path"
        name: "id"
        description: "Identificador de la reserva"
        required: true
        type: string
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Operación satisfactoria"
          schema:
            type: "array"
            items: 
              type: "object"
              $ref: "#/definitions/Reserva"
        "404":
          description: "No encontrada"
 
  
definitions:
  Reserva:
    type: "object"
    properties:
      id_vehiculo:
        type: "integer"
        format: "int64"
      id_cliente:
        type: "integer"
        format: "int64"
      estado:
        type: "string"
      creacion_datetime:
        type: "string"
      expiracion_datetime:
        type: "string"
  ReservaEntrada:
    type: "object"
    properties:
      id_vehiculo:
        type: "integer"
        format: "int64"
      id_cliente:
        type: "integer"
        format: "int64"